-- EXEMPLOS DE USO - JOINS ###################################################################

-- (Exemplo 1) Identifique qual é o status profissional mais frequente nos clientes 
-- que compraram automóveis no site
SELECT CUS.PROFESSIONAL_STATUS,
	COUNT(FUN.PAID_DATE) AS PAGAMENTOS
FROM SALES.FUNNEL AS FUN
LEFT JOIN SALES.CUSTOMERS AS CUS
ON FUN.CUSTOMER_ID = CUS.CUSTOMER_ID
GROUP BY CUS.PROFESSIONAL_STATUS
ORDER BY PAGAMENTOS DESC;


-- (Exemplo 2) Identifique qual é o gênero mais frequente nos clientes que compraram
-- automóveis no site. Obs: Utilizar a tabela temp_tables.ibge_genders
SELECT *
FROM TEMP_TABLES.IBGE_GENDERS
LIMIT 10;

SELECT IBGE.GENDER,
	COUNT(FUN.PAID_DATE)
FROM SALES.FUNNEL AS FUN
LEFT JOIN SALES.CUSTOMERS AS CUS
ON FUN.CUSTOMER_ID = CUS.CUSTOMER_ID
LEFT JOIN TEMP_TABLES.IBGE_GENDERS AS IBGE
ON LOWER(CUS.FIRST_NAME) = IBGE.FIRST_NAME
GROUP BY IBGE.GENDER;

-- (Exemplo 3) Identifique de quais regiões são os clientes que mais visitam o site
-- Obs: Utilizar a tabela temp_tables.regions
SELECT *
FROM SALES.CUSTOMERS
LIMIT 10;

SELECT *
FROM TEMP_TABLES.REGIONS
LIMIT 10;

SELECT REG.REGION,
	COUNT(FUN.VISIT_PAGE_DATE) AS VISITAS
FROM SALES.FUNNEL AS FUN
LEFT JOIN SALES.CUSTOMERS AS CUS
ON FUN.CUSTOMER_ID = CUS.CUSTOMER_ID
LEFT JOIN TEMP_TABLES.REGIONS AS REG
ON LOWER(CUS.CITY) = LOWER(REG.CITY)
AND LOWER(CUS.STATE) = LOWER(REG.STATE)
GROUP BY REG.REGION
ORDER BY VISITAS DESC;

